import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import { Layout } from "antd";
import { Content, Header } from "antd/es/layout/layout";
import Navigation from "./ui/Navigation";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<AntdRegistry>
					<Layout>
						<Header className="fixed w-full z-50">
							<Navigation />
						</Header>
						<Content className="pt-20 pb-10 !min-h-[100vh]">
							<div className="container mx-auto">{children}</div>
						</Content>
					</Layout>
				</AntdRegistry>
			</body>
		</html>
	);
}
